### ISSUE TITLE
sass-like comments get removed on save

### ISSUE THREAD

**Issue by hyperupcall** [replit-discord/carnival#30]
**describe the bug**
sass-like comments get removed on file save when writing css

**to reproduce**
1. `yarn dev`
2. add any sass-like comment to a style block

**expected behavior**
comment does not get removed

**Comment by eankeen** [comment]
comments only are removed if it directly follows a css rule like so:

```scss
h1 {
  will-change: auto; // comment
}
```

i tried replacing `postcss-strip-inline-comments` with `postcss-comment`, but i may only be able to do that in a `postcss.config.js` file (since it does not seem to export the postcss plugin like other plugins (it seems to need to be imported like `require('postcss-comment/hookRequire')`?)

anyone is welcome to fix this if they can get it to work
